version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -V
      - run: pip install -r requirements.txt
      - run: python -m unittest -v
workflows:
  ci:
    jobs:
      - test
